language: go

go:
  - 1.x

services:
  - docker

jobs:
  include:
    - os: linux
      dist: focal

install:
  - for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc docker; do sudo apt-get remove $pkg; done
  - curl "https://get.docker.com/" -o install_docker.sh
  - chmod +x install_docker.sh
  - sudo ./install_docker.sh --version 25
  - go get ./...

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

script:
  - ./run.sh
